export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  console.log("Montando layout global");

  return (
    <html lang="en">
      <body>
        <nav>
          <a href="/">Home</a> | <a href="/novarota">Nova Rota</a> | <a href="/outrarota">Outra Rota</a>
        </nav>
        {children}
      </body>
    </html>
  );
}

export default function NovaRotaLayout({ children }) {
  console.log("Montando layout da Nova Rota");

  return (
    <div>
      <header>
        <h1>Nova Rota</h1>
      </header>
      <main>{children}</main>
    </div>
  );
}

export default function OutraRotaLayout({ children }) {
  console.log("Montando layout da Outra Rota");

  return (
    <section>
      <h2>Seja bem-vindo à Outra Rota!</h2>
      {children}
    </section>
  );
}
